import { StyleSheet } from "react-native";

export const form = StyleSheet.create({
  container: {
    backgroundColor: "#0e0b29",
    flex: 1,
    paddingTop: 100,
    justifyContent: "flex-start",
    color: "white",
  },

  formTittle: {
    fontSize: 35,
    fontWeight: "bold",
    color: "white",
    textAlign: "center",
  },

  inputContainer: {
    paddingBottom: 15,
    // marginTop: 20,
    // backgroundColor: "rgba(255, 255, 255, 0.3)",
    borderRadius: 7,
    width: "80%",
    alignSelf: "center",
  },

  inputs: {
    width: "90%",
    alignSelf: "center",
    fontSize: 18,
    fontWeight: "600",
    paddingVertical: 10,
    paddingLeft: 20,
    borderWidth: 2,
    borderRadius: 7,
    borderColor: "white",
    paddingRight: 12,
    marginBottom: 30,
    backgroundColor: "white",
  },

  colorBtn: {
    alignSelf: "center",
    marginTop: 20,
    width: "90%",
    borderWidth: 1,
    borderColor: "#f27e18",
    backgroundColor: "#e69249",
    padding: 15,
    marginHorizontal: 20,
    borderRadius: 7,
  },

  colorTxtBtn: {
    color: "#FFFFFF",
    fontSize: 16,
    textAlign: "center",
  },
  registerTxtBtn: {
    marginTop: 20,
    color: "#e69249",
    fontSize: 16,
    textAlign: "center",
  },
  registerOptContainer: {
    marginTop: 30,
  },
  errorText: {
    width: "100%",
    color: "red",
    backgroundColor: "white",
  },
  errorContainer: {
    alignSelf: "center",
    width: "80%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 0,
    marginBottom: 10,
  },
});

export const formR = StyleSheet.create({
  container: {
    backgroundColor: "#0e0b29",
    flex: 1,
    paddingTop: 100,
    justifyContent: "flex-start",
    color: "white",
  },
  formTittle: {
    fontSize: 35,
    fontWeight: "400",
    color: "white",
    textAlign: "center",
  },
  inputContainer: {
    marginTop: 20,
    backgroundColor: "rgba(255, 255, 255, 0.3)",
    borderRadius: 7,
    width: "80%",
    alignSelf: "center",
  },
  inputs: {
    width: "80%",
    alignSelf: "center",
    fontSize: 18,
    fontWeight: "600",
    paddingLeft: 20,
    paddingVertical: 10,
    borderWidth: 2,
    borderRadius: 7,
    borderColor: "white",
    paddingRight: 12,
    marginTop: 15,
    marginBottom: 15,
    backgroundColor: "white",
  },
  customInput: {
    width: "80%",
    alignSelf: "center",
    fontWeight: "600",
    marginVertical: 5,
    display: "flex",
    flexDirection: "row",
  },
  textCustomInput: {
    color: "white",
    fontSize: 18,
    alignSelf: "center",
  },
  error: {
    color: "black",
    width: "80%",
    alignSelf: "center",
  },
  colorBtn: {
    alignSelf: "center",
    width: "50%",
    borderWidth: 1,
    borderColor: "#f27e18",
    backgroundColor: "#e69249",
    padding: 15,
    marginTop: 20,
    marginLeft: 20,
    marginRight: 20,
    borderRadius: 7,
  },
  leagueFormBtn: {
    alignSelf: "center",
    borderWidth: 1,
    borderColor: "#f27e18",
    padding: 15,
    marginTop: 20,
    marginLeft: 20,
    marginRight: 20,
    borderRadius: 7,
  },
  colorTxtBtn: {
    color: "#FFFFFF",
    fontSize: 18,
    textAlign: "center",
  },
});
